package com.aisino.protocol.bean;
/**
 * 获取电商企业信息报文头
 * 
 * @author 梁国栋
 * 2014-10-23
 */
public class RESPONSE_COMMON_DJDSQYXXGLOBLE {

	  private String RETURNCODE;
	    private String RETURNMESSAGE;
	    private RESPONSE_COMMON_DJDSQYXX[] RESPONSE_COMMON_DJDSQYXXS;
	    private RESPONSE_COMMON_DSQYPZHDXX[] RESPONSE_COMMON_DSQYPZHDXXS ;
		public String getRETURNCODE() {
			return RETURNCODE;
		}
		public void setRETURNCODE(String rETURNCODE) {
			RETURNCODE = rETURNCODE;
		}
		public String getRETURNMESSAGE() {
			return RETURNMESSAGE;
		}
		public void setRETURNMESSAGE(String rETURNMESSAGE) {
			RETURNMESSAGE = rETURNMESSAGE;
		}
		public RESPONSE_COMMON_DJDSQYXX[] getRESPONSE_COMMON_DJDSQYXXS() {
			return RESPONSE_COMMON_DJDSQYXXS;
		}
		public void setRESPONSE_COMMON_DJDSQYXXS(
				RESPONSE_COMMON_DJDSQYXX[] rESPONSECOMMONDJDSQYXXS) {
			RESPONSE_COMMON_DJDSQYXXS = rESPONSECOMMONDJDSQYXXS;
		}
		public RESPONSE_COMMON_DSQYPZHDXX[] getRESPONSE_COMMON_DSQYPZHDXXS() {
			return RESPONSE_COMMON_DSQYPZHDXXS;
		}
		public void setRESPONSE_COMMON_DSQYPZHDXXS(
				RESPONSE_COMMON_DSQYPZHDXX[] rESPONSECOMMONDSQYPZHDXXS) {
			RESPONSE_COMMON_DSQYPZHDXXS = rESPONSECOMMONDSQYPZHDXXS;
		}
		
}
