package com.aisino.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * IEInvWebServiceService service = new IEInvWebServiceService();
 * IEInvWebService portType = service.getIEInvWebServicePort();
 * portType.eiInterface(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "IEInvWebServiceService", targetNamespace = "http://impl.ws.aisino.com/", wsdlLocation = "http://localhost:8087/51pt_zzssl/webservice/eInvWS?wsdl")
public class IEInvWebServiceService extends Service {

    private final static URL IEINVWEBSERVICESERVICE_WSDL_LOCATION;

    private final static Logger logger = Logger
            .getLogger(IEInvWebServiceService.class
                    .getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = IEInvWebServiceService.class
                    .getResource(".");
            url = new URL(baseUrl,
                    "http://localhost:8087/51pt_zzssl/webservice/eInvWS?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8087/51pt_zzssl/webservice/eInvWS?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IEINVWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public IEInvWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IEInvWebServiceService() {
        super(IEINVWEBSERVICESERVICE_WSDL_LOCATION, new QName(
                "http://impl.ws.aisino.com/", "IEInvWebServiceService"));
    }

    /**
     * 
     * @return returns IEInvWebService
     */
    @WebEndpoint(name = "IEInvWebServicePort")
    public IEInvWebService getIEInvWebServicePort() {
        return super.getPort(new QName("http://impl.ws.aisino.com/",
                "IEInvWebServicePort"), IEInvWebService.class);
    }

}
