package com.aisino.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12
 * Wed Apr 09 11:11:59 GMT+08:00 2014
 * Generated source version: 2.2.12
 * 
 */
 
@WebService(targetNamespace = "http://www.jd.com", name = "ReceiveShangHai")
@XmlSeeAlso({ObjectFactory.class})
public interface ReceiveShangHai {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getHashTime", targetNamespace = "http://www.jd.com", className = "com.aisino.cxf.client.GetHashTime")
    @WebMethod
    @ResponseWrapper(localName = "getHashTimeResponse", targetNamespace = "http://www.jd.com", className = "com.aisino.cxf.client.GetHashTimeResponse")
    public EiActualBill getHashTime(
            @WebParam(name = "arg0", targetNamespace = "")
                    Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "receive", targetNamespace = "http://www.jd.com", className = "com.aisino.cxf.client.Receive")
    @WebMethod
    @ResponseWrapper(localName = "receiveResponse", targetNamespace = "http://www.jd.com", className = "com.aisino.cxf.client.ReceiveResponse")
    public String receive(
            @WebParam(name = "invoiceXml", targetNamespace = "")
                    String invoiceXml
    );
}
