
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.aisino.cxf.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12
 * Wed Apr 09 11:11:59 GMT+08:00 2014
 * Generated source version: 2.2.12
 * 
 */

@WebService(
                      serviceName = "ReceiveShangHaiService",
                      portName = "ReceiveShangHaiPort",
                      targetNamespace = "http://www.jd.com",
                      wsdlLocation = "http://eicore.test.jd.com/services/receiveShangHai?wsdl",
                      endpointInterface = "com.aisino.cxf.client.ReceiveShangHai")
                      
public class ReceiveShangHaiImpl implements ReceiveShangHai {

    private static final Logger LOG = Logger.getLogger(ReceiveShangHaiImpl.class.getName());

    /* (non-Javadoc)
     * @see com.aisino.cxf.client.ReceiveShangHai#getHashTime(java.lang.Long  arg0 )*
     */
    public EiActualBill getHashTime(Long arg0) {
        LOG.info("Executing operation getHashTime");
        System.out.println(arg0);
        try {
            EiActualBill _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aisino.cxf.client.ReceiveShangHai#receive(java.lang.String  invoiceXml )*
     */
    public String receive(String invoiceXml) {
        LOG.info("Executing operation receive");
        System.out.println(invoiceXml);
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
