package com.aisino.protocol.bean;

/**
 * 增值税接口对接
 * 
 * @author jerome
 * 
 */
public class REQUEST_COMMON_FPKJ {
	public COMMON_FPKJ_FPT COMMON_FPKJ_FPT;
	public COMMON_FPKJ_XMXX[] COMMON_FPKJ_XMXXS;
	public COMMON_FPKJ_DDXX COMMON_FPKJ_DDXX;
	public COMMON_FPKJ_ZFXX COMMON_FPKJ_ZFXX;
	public COMMON_FPKJ_WLXX COMMON_FPKJ_WLXX;
//	public FPKJXX_DDMXXX[] FPKJXX_DDMXXXS;

	public COMMON_FPKJ_FPT getCOMMON_FPKJ_FPT() {
		return COMMON_FPKJ_FPT;
	}

	public void setCOMMON_FPKJ_FPT(COMMON_FPKJ_FPT cOMMON_FPKJ_FPT) {
		COMMON_FPKJ_FPT = cOMMON_FPKJ_FPT;
	}

	public COMMON_FPKJ_XMXX[] getCOMMON_FPKJ_XMXXS() {
		return COMMON_FPKJ_XMXXS;
	}

	public void setCOMMON_FPKJ_XMXXS(COMMON_FPKJ_XMXX[] cOMMON_FPKJ_XMXXS) {
		COMMON_FPKJ_XMXXS = cOMMON_FPKJ_XMXXS;
	}

	public COMMON_FPKJ_DDXX getCOMMON_FPKJ_DDXX() {
		return COMMON_FPKJ_DDXX;
	}

	public void setCOMMON_FPKJ_DDXX(COMMON_FPKJ_DDXX cOMMON_FPKJ_DDXX) {
		COMMON_FPKJ_DDXX = cOMMON_FPKJ_DDXX;
	}

	public COMMON_FPKJ_ZFXX getCOMMON_FPKJ_ZFXX() {
		return COMMON_FPKJ_ZFXX;
	}

	public void setCOMMON_FPKJ_ZFXX(COMMON_FPKJ_ZFXX cOMMON_FPKJ_ZFXX) {
		COMMON_FPKJ_ZFXX = cOMMON_FPKJ_ZFXX;
	}

	public COMMON_FPKJ_WLXX getCOMMON_FPKJ_WLXX() {
		return COMMON_FPKJ_WLXX;
	}

	public void setCOMMON_FPKJ_WLXX(COMMON_FPKJ_WLXX cOMMON_FPKJ_WLXX) {
		COMMON_FPKJ_WLXX = cOMMON_FPKJ_WLXX;
	}

//	public FPKJXX_DDMXXX[] getFPKJXX_DDMXXXS() {
//		return FPKJXX_DDMXXXS;
//	}
//
//	public void setFPKJXX_DDMXXXS(FPKJXX_DDMXXX[] fPKJXX_DDMXXXS) {
//		FPKJXX_DDMXXXS = fPKJXX_DDMXXXS;
//	}
}
